In [3]:
!git clone https://github.com/zhangbo2008/opensource_tts_chinese_and_english

Cloning into 'opensource_tts_chinese_and_english'...
remote: Enumerating objects: 2640, done.
remote: Total 2640 (delta 0), reused 0 (delta 0), pack-reused 2640
Receiving objects: 100% (2640/2640), 54.93 MiB | 23.48 MiB/s, done.
Resolving deltas: 100% (971/971), done.


In [29]:
%cd opensource_tts_chinese_and_english

/kaggle/working/opensource_tts_chinese_and_english


In [30]:
!ls

11.wav			 666		 chinese_tts2.py
2.mp3			 8888.py	 detr_model_debug.py
2021-06-16-16-29-56.wav  ChineseASR.py	 english_tts.py
2021-07-01-17-42-26.wav  EnglishASR.py	 readme.md
2222222.py		 TensorFlowTTS	 tensorflow_tts
22English.wav		 __init__.py	 test.tsv
3333333.py		 audio.wav	 transformers
444.py			 chinese.wav	 vit_model_debug.py
444的语音文件.flac	 chinese_asr.py  刷时间.py
65555.py		 chinese_tts.py  语音识别中文字典


In [17]:
!pip install tensorflow==2.12.0


In [37]:
!pip install jamo inflect pypinyin  tensorflow_addons  g2p_en


  Using cached g2p_en-2.1.0-py3-none-any.whl (3.1 MB)
  Using cached Distance-0.1.3-py3-none-any.whl


In [38]:
import numpy as np
import soundfile as sf
import yaml

import tensorflow as tf

# 我说明一下tts的逻辑:
# 这个项目首先需要 文字转编码, 用 processor
# 然后 编码啊转mel序列. 用fastspeech2
# 最后mel序列转语音 用model = TFAutoModel.from_pretrained("tensorspeech/tts-mb_melgan-baker-ch")


from tensorflow_tts.inference import AutoProcessor
from tensorflow_tts.inference import TFAutoModel

processor = AutoProcessor.from_pretrained("tensorspeech/tts-fastspeech2-baker-ch")
fastspeech2 = TFAutoModel.from_pretrained("tensorspeech/tts-fastspeech2-baker-ch")
from tensorflow_tts.inference import TFAutoModel

model = TFAutoModel.from_pretrained("tensorspeech/tts-mb_melgan-baker-ch")

text = "这是一个开源的端到端中文语音合成系统"

input_ids = processor.text_to_sequence(text, inference=True)

mel_before, mel_after, duration_outputs, _, _ = fastspeech2.inference(
    input_ids=tf.expand_dims(tf.convert_to_tensor(input_ids, dtype=tf.int32), 0),
    speaker_ids=tf.convert_to_tensor([0], dtype=tf.int32),
    speed_ratios=tf.convert_to_tensor([1.0], dtype=tf.float32),
    f0_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32),
    energy_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32),
)

audios = model.inference(mel_after)[0, :, 0]
print(1)



# save to file
import time
a=time.time()
import time
now = time.localtime()
nowt = time.strftime("%Y-%m-%d-%H-%M-%S", now)  #这一步就是对时间进行格式化
print(nowt)
sf.write(f'./{nowt}.wav', audios, 22050, 'PCM_24')
print('名字是')
print(f'./{nowt}.wav')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /usr/share/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package cmudict to /usr/share/nltk_data...
[nltk_data]   Package cmudict is already up-to-date!


/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:649: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(


phoneme seq: sil zh e4 #0 sh iii4 #0 ^ i2 #0 g e4 #0 k ai1 #0 ^ van2 #0 d e5 #0 d uan1 #0 d ao4 #0 d uan1 #0 zh ong1 #0 ^ uen2 #0 ^ v3 #0 ^ in1 #0 h e2 #0 ch eng2 #0 x i4 #0 t ong3 sil
1
2023-09-01-03-01-42


In [40]:
audios

<tf.Tensor: shape=(78300,), dtype=float32, numpy=
array([-6.99192460e-05, -8.28042685e-05, -1.59231000e-04, ...,
       -3.07010741e-05,  1.07405085e-05,  3.68259571e-05], dtype=float32)>

In [43]:
audios.numpy()

array([-6.99192460e-05, -8.28042685e-05, -1.59231000e-04, ...,
       -3.07010741e-05,  1.07405085e-05,  3.68259571e-05], dtype=float32)

In [45]:
print(f'./{nowt}.wav')

./2023-09-01-03-01-42.wav


In [51]:
from IPython.display import Audio


Audio(audios.numpy(), rate=22050)

